#!/bin/bash

# TODO vendor all network dependecies

# Assuming your base is raspbian-ua-netinst
# NetpocketOS base OS will be installed on top

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NOS=/opt/netpocketos
if [[ ! -d $NOS ]]; then
  if [[ ! "$DIR" -eq "$NOS" ]]; then
    mv $DIR $NOS
  fi
fi

if [[ ! -f $NOS/server.js ]]; then
  echo "failed to establish source directory"
  exit 127
fi

if ! hash node 2>/dev/null; then
  nodetar=$NOS/vendor/node-v0.10.24-linux-arm-armv6j-vfp-hard.tar.gz
  cd /usr/local
  tar xzvf $nodetar --strip=1
fi

if ! hash node 2>/dev/null; then
  echo "failed to install node.js !"
  exit 127
fi


cd $NOS

cat > $NOS/init <<EOF
#!/bin/sh
$(which forever) stop $NOS/server.js"
export NOS_TOKEN=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1)
export RELAY_SERVER=http://ncc-relay.herokuapp.com
export NODE_ENV=production
$(which forever) start -l $NOS/nos.log -a $NOS/server.js"
EOF

cat > /etc/rc.local <<EOF
#!/bin/sh -e
su - root "$NOS/init"
exit 0
EOF

echo "starting netpocketos"
/etc/rc.local
forever list
